services:
  - type: web
    name: fecabasket
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fecabasket.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fecabasket_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_COLLECTSTATIC
        value: "1"