# Generated by Django 4.1.11 on 2025-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nom', models.CharField(max_length=100)),
                ('nom_dirigeant', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('entraineur', models.CharField(blank=True, max_length=100, null=True)),
                ('dossier', models.FileField(blank=True, null=True, upload_to='dossiers/')),
                ('palmares', models.TextField(blank=True, null=True)),
                ('couleurs_maillot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entraineur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='entraineurs/')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('lieu_residence', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('club', models.CharField(max_length=100)),
                ('dossier', models.FileField(blank=True, null=True, upload_to='dossiers_entraineurs/')),
                ('palmares', models.TextField(blank=True, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='joueurs/')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('main_forte', models.CharField(choices=[('Droite', 'Droite'), ('Gauche', 'Gauche'), ('Ambidextre', 'Ambidextre')], default='Droite', max_length=10)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('envergure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('dossard', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reseaux_sociaux', models.TextField(blank=True, null=True)),
                ('annee_inscription', models.IntegerField(blank=True, null=True)),
                ('nom_etablissement', models.CharField(blank=True, max_length=150, null=True)),
                ('classe_frequentee', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_parent_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_parent_1', models.CharField(blank=True, max_length=15, null=True)),
                ('nom_parent_2', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_parent_2', models.CharField(blank=True, max_length=15, null=True)),
                ('passions', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='Actif', max_length=10)),
                ('dossier', models.FileField(blank=True, null=True, upload_to='dossiers_joueurs/')),
                ('club', models.CharField(blank=True, max_length=255, null=True)),
                ('ligue', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('lieu_residence', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='officiels/')),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
    ]
